#!/bin/bash

# Note, requires:
#    libgmp-dev libmpc-dev libmpfr-dev fastjar zip

if [ -z "$1" ]; then
    echo "Usage: $0 <install_location>"
    exit -1
fi

function make_dir()
{
    rm -rf "$1"
    mkdir "$1"
}

cd $1
INSTALL_DIR=$PWD
GCC_TRUNK="svn://gcc.gnu.org/svn/gcc/trunk"
CPU_CORES="$(grep -c ^processor /proc/cpuinfo)"
GCC_DIR="$INSTALL_DIR/gcc"
SRC_DIR="$GCC_DIR/src"
BUILD_DIR="$GCC_DIR/build"
DIST_DIR="$GCC_DIR/dist"

# Directory setup
make_dir $GCC_DIR
make_dir $SRC_DIR
make_dir $BUILD_DIR
make_dir $DIST_DIR

# Checkout source
svn co $GCC_TRUNK $SRC_DIR

# Configuration
cd $BUILD_DIR
$SRC_DIR/./configure --prefix=$DIST_DIR --enable-languages=c,c++ --disable-multilib

# Build
make -j $CPU_CORES
